### ISSUE TITLE
Unable to set caBundle correctly

### ISSUE THREAD

**Issue by EliSauder** [djkormo/adcs-issuer#103]
This issue is likely me being stupid, but I cannot figure out how to get the caBundle of the clusterIssuer to work correctly. I am pulling the cert of our issuer as a PEM, copying the base64 content as a single line, and setting spec.caBundle to that value. Example:
```yaml
spec:
  caBundle: "My base64 cert without header and footer"
```

However when I then go to actually load it into the cluster I am getting this error:
`Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 3`

Is there some secret ritual I need to do to get the kubernete deities to look favorably upon my cert?

**Comment by EliSauder** [comment]
Turns out, it was my own stupidity; I hadn't encoded the username and password in the credentials...

**Comment by djkormo** [comment]
You're welcome.
