### ISSUE TITLE
Update Installation Documentation

### ISSUE THREAD

**Issue by rajsinghtech** [djkormo/adcs-issuer#19]
After much struggle I cannot get a grasp on how to install this. Could you provide some more info in the documentation! I want to use this cool project.

**Comment by djkormo** [comment]
I was thinking about creating helm chart for this plugin. Are you interested ?

**Comment by rajsinghtech** [comment]
Yeah I would be interested for sure!

**Comment by djkormo** [comment]
https://djkormo.github.io/adcs-issuer/
At the bottom of gitub page.

**Comment by rajsinghtech** [comment]
Awesome will try this out
