### ISSUE TITLE
Make helm charts more customizable

### ISSUE THREAD

**Issue by Khaos66** [djkormo/adcs-issuer#89]
The current chart is very strict.

Switching to a chart library template would give the chart instantly a lot more flexibility.
I used [Common library](https://bjw-s.github.io/helm-charts/docs/common-library/) recently and it's a treat

**Comment by Khaos66** [comment]
here is where and how I used this chart lib: https://github.com/Khaos66/BaGetter/tree/main/chart/bagetter

**Comment by djkormo** [comment]
With 3.0.0 helm chart version we have a lot of changes. Could you review them ?

**Comment by Khaos66** [comment]
Well, I'm not an expert on this topic. 
I see you've put a lot of effort in the charts <3
While I still think going with Common Library would have been beneficial, as it brings all the common options, I accept your decision not to use it.
My use cases are covered by the current chart, so I'll close the ticket.
