### ISSUE TITLE
Incorrect Tag in values.yaml?

### ISSUE THREAD

**Issue by awickham10** [djkormo/adcs-issuer#94]
I noticed in values.yaml, it's still pointing to 2.1.0 even though 2.1.1 is mentioned as the latest release. Is this accurate?

https://github.com/djkormo/adcs-issuer/blob/ae5eb471c11eebe3aaf45129e8d5bd3da11bc3ce/charts/adcs-issuer/values.yaml#L11

**Comment by djkormo** [comment]
You can use version 2.1.1

**Comment by djkormo** [comment]
Version 3.0.0 of chelm chart is releases.
